// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jffqippnoauiyfpnvgim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmZnFpcHBub2F1aXlmcG52Z2ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODA4OTIsImV4cCI6MjA3MjQ1Njg5Mn0.xSx2UNdAxpieBtckkzBTBxa7ts79YQboqTY7GlD0iAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});